apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ffjuaq2ns-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-21408c570e.clc8.p3.openshiftapps.com/rhtap/rhtap-qe:26522b64407d3f882c4bd3dceea522a7142c27fe@sha256:0ca7aa5faf48aabda73e3f1280a57a0aea973633903e62a641266b0ef9726680
          name: container-image
